# site-wide configuration
# https://gohugo.io/variables/site/
baseURL: "https://darrenkwondev.github.io/"
languageCode: "en-us"
lang: "en"
title: "darrenkwon.dev blog"
theme: "hugo-dead-simple"

params:
    author: drkdev
    Subtitle: software
    roseIcon: false
    description: "software development blog"

menu:
    main:
        - name: "Home"
          url: "/"
          weight: 1
        - name: "Tags"
          url: "tags/"
          weight: 2
        - name: "About"
          url: "about/"
          weight: 3

# https://gohugo.io/getting-started/configuration-markup/
markup:
    # highlight:
    #     codeFences: true
    #     style: bw
    #     lineNumbersInTable: false
    #     noClasses: false
    goldmark:
        renderer:
            unsafe: true # for html tags in markdown

outputs:
    home:
        - html
        - rss
        - json
    page:
        - html
