baseURL: "https://darrenkwondev.github.io/"
languageCode: "en-us"
title: "darrenkwon.dev"
theme: "hugo-dead-simple"
menu:
    main:
        - name: "Home"
          url: "/"
          weight: 1
        - name: "Tags"
          url: "tags/"
          weight: 2
        # - name: "Contact"
        #   url: "contact/"
        #   weight: 3
