baseURL: "https://darrenkwondev.github.io/"
languageCode: "en-us"
title: "darrenkwon.dev"
theme: "hugo-dead-simple"
menu:
    main:
        - name: "Home"
          url: "/"
          weight: 1
        - name: "Tags"
          url: "tags/"
          weight: 2
        # - name: "Contact"
        #   url: "contact/"
        #   weight: 3

markup:
    # highlight:
    #     codeFences: true
    #     style: bw
    #     lineNumbersInTable: false
    #     noClasses: false
    goldmark: # https://github.com/yuin/goldmark
        renderer:
            unsafe: true # for html tags in markdown

outputs:
    home:
        - html
        - rss
        - json
    page:
        - html
